### ISSUE TITLE
Evaluación intermedia

### ISSUE THREAD

**Issue by profes-adalab** [Adalab/modulo-2-evaluacion-intermedia-alicia-colom#1]
Really cool job @alicia-colom  !!!

Here you have some tips to improve the exercise:

### JavaScript: advanced

- [x] Move the feedback logic to a function and execute it on each click.
- [x] Move you counter logic into a function and execute it on each click.

### JavaScript: good practices

- [x] Move variables and constants declarations to the top of the file.

### Good practices

- [x] Remove unnecessary commented code.
- [x] Try to improve your commits messages. "Add JS" is a bit poor. "Add random number logic" is more explanatory.

### Structure

- [x] Define a good structure of folders and files for the project.

### HTML

- [x] Add form
- [x] Use placeholder attribute instead of value one to show a field's hint.
- [x] Use placeholder.

### CSS

- [x] Avoid adding styles until the js code is solid as a rock.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by alicia-colom** [comment]
Thank you so much for your report! :)

I have some doubts:

**HTML:** 

> - "_Add form_". I reviewed my HTML file and it has already the `form` inside (this form includes one label and two inputs elements: text box  and button). That's why I'm not sure about what is it asking me to improve. Could you clarify it?
> 
> - "_Use placeholder attribute instead of value one to show a field's hint_." I don't know if it means that I have to change the `value` in button input for a `placeholder`... I has no sense for me, beause I need the attribute `value` in order to write on the button. 


**Structure:**

> - "_Define a good structure of folders and files for the project_." I thought create a full structure of folders won't be necesary in this exercise, because it only works with 3 files (.HTML + .CSS + .JS). I fix this issue creating 3 folders, one for each file (./html + ./css + ./js). Is it ok with this change?


**JavaScript: advanced:**

> - "_Move the feedback logic to a function and execute it on each click_." I don't understand this change, because I had put the conditional feedback into the handle function, so it is executed in each click on the button "Prueba". Could you clarify it?

> - "_Move you counter logic into a function and execute it on each click_." I don't understand this change, because I had put the counter into the handle function, so it is executed in each click on the button "Prueba". Could you clarify it?


I'll be waiting your answer. 
Meanwhile, I'll be trying to improve some of "Further challenges" you suggest, in order to keep practising  :)

Thank you!

**Comment by alicia-colom** [comment]
Hello again!
I have playing with my exercise! :)
And I got done some improvements on it: 
> - Add new feedback when the number is bigger than 100 and when is smaller than 0.
> - Manage when the user hits the button and the input is empty.
> - Manage the button when the user wins.
> - Add a reset button that cleans the input, the counter, writes the initial feedback, generates a new random number to play again, and change CSS classes in both buttons to let guide the user.

:)
